name: Build Android APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build with Buildozer
      uses: ArtemShorokhov/buildozer-action@v1
      with:
        command: buildozer -v android debug
        subfolder: .

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: bin/*.apk
        
